---

- name: Check If Splunk Forwarder is Already Installed
  stat:
    path: /opt/splunkforwarder/bin/splunk
  register: splunkInstalled
  ignore_errors: true

- name: Download Splunk Universal Forward Binary
  get_url:
    url: "{{ splunkUFURL }}"
    dest: /tmp/splunkUF.tgz
  when: not splunkInstalled.stat.exists

- name: Install Splunk Universal Forwarder
  unarchive:
    src: /tmp/splunkUF.tgz
    dest: /opt/
    remote_src: true
  when: not splunkInstalled.stat.exists

- name: Create splunk user
  user:
    name: splunk
    state: present
    home: /opt/splunkforwarder

- name: Create splunk user bashrc file
  file:
    path: /opt/splunkforwarder/.bashrc
    state: touch
    owner: splunk
    group: splunk

- name: Set SPLUNK_HOME var
  lineinfile: 
    path: /opt/splunkforwarder/.bashrc
    line: "export SPLUNK_HOME=/opt/splunkforwarder"
    state: present

- name: Configure Splunk user-seed.conf file
  ini_file:
    path: /opt/splunkforwarder/etc/system/default/user-seed.conf
    owner: splunk
    mode: 0700
    section: user_info
    option: USERNAME
    value: admin
  when: not splunkInstalled.stat.exists

- name: Configure Splunk user-seed.conf file round 2
  ini_file:
    path: /opt/splunkforwarder/etc/system/default/user-seed.conf
    owner: splunk
    mode: 0700
    section: user_info
    option: PASSWORD
    value: "{{splunkUFAdminPassword}}"
  when: not splunkInstalled.stat.exists

- name: Set Permissions on /opt/splunkforwarder
  file:
    name: /opt/splunkforwarder
    recurse: yes
    owner: splunk
    group: splunk
  when: not splunkInstalled.stat.exists

- name: Start Splunk For First Time
  become_user: splunk
  command: /opt/splunkforwarder/bin/splunk start --accept-license
  when: not splunkInstalled.stat.exists

- name: Stop Splunk
  become_user: splunk
  command: /opt/splunkforwarder/bin/splunk stop
  when: not splunkInstalled.stat.exists

- name: Enable Splunk to Start on Boot
  command: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk -systemd-managed 1
  when: not splunkInstalled.stat.exists

- name: Verify Splunk user-seed.conf File is Removed
  file:
    path: /opt/splunkforwarder/etc/system/default/user-seed.conf
    state: absent
