---

- name: Manage Nessus Image
  docker_image:
    state: present
    name: tenableofficial/nessus
    force_source: yes
    source: pull

- name: Create Nessus Container
  docker_container:
    detach: true
    name: nessus
    image: tenableofficial/nessus
    env:
        USERNAME: "{{ nessusUsername }}"
        PASSWORD: "{{ nessusPassword }}"
    labels:
      traefik.http.routers.nessus.tls: "true"
      traefik.http.services.nessus.loadbalancer.server.scheme: "https"
      traefik.http.services.nessus.loadbalancer.server.port: "8834"
    log_driver: splunk
    log_options:
      splunk-token: "{{ containerHECToken }}"
      splunk-url: "{{ containerHECDestination }}"
      splunk-insecureskipverify: true
      splunk-index: containers
      splunk-source: nessus
      splunk-sourcetype: syslog
      splunk-verify-connection: false
    state: started
    restart_policy: unless-stopped
    privileged: true
    published_ports:
      - 8834:8834