---

- name: Create partitions
  parted:
    device: /dev/sda
    number: 1
    state: present
    label: gpt
  ignore_errors: true

- name: Create a xfs filesystems
  filesystem:
    fstype: xfs
    dev: /dev/sda1
    force: "{{ overWritePartition }}"

- name: Create directories
  file:
    path: /opt/external
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Mount volumes
  mount:
    path: /opt/external
    src: /dev/sda1
    fstype: xfs
    state: mounted
