---

- name: Create minio Splunk directory
  file:
    path: /opt/external/minioSplunk/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Manage minio image
  docker_image:
    state: present
    name: minio/minio
    force_source: yes
    source: pull

- name: Create minio Container
  docker_container:
    detach: true
    name: minio
    image: minio/minio
    state: started
    restart_policy: unless-stopped
    labels:
      traefik.http.routers.minio.tls: "true"
      traefik.http.services.minio.loadbalancer.server.port: "9000"
    command: server --console-address ":9003" /data
    published_ports:
      - 9000:9000
    env:
        MINIO_ROOT_USER: "{{ minioAccessKey }}"
        MINIO_ROOT_PASSWORD: "{{ minioSecretKey }}"
    volumes:
      - /opt/external/minioSplunk/:/data:Z
    log_driver: splunk
    log_options:
      splunk-token: "{{ splunkContainerHECToken }}"
      splunk-url: "https://{{ splunkHECDestination }}:8088"
      splunk-insecureskipverify: true
      splunk-index: containers
      splunk-source: minio
      splunk-sourcetype: syslog
      splunk-verify-connection: false
