---

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
    lock_timeout: 600

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0

- name: Install docker
  yum:
    name: ['docker-ce', 'python-docker-py']
    state: latest
    lock_timeout: 600

- name: Enable Docker Service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Install pip
  yum:
    name: python3-pip
    state: latest

- name: Install Docker-py
  pip:
    name: docker-py
    executable: pip3.6
