---

- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest
    lock_timeout: 600

- name: Enable Docker repo
  shell: "yum-config-manager  --add-repo  https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install docker
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
    lock_timeout: 600

- name: Enable Docker Service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Install pip
  yum:
    name: python3-pip
    state: latest

- name: Install Docker-py
  pip:
    name: docker-py
    executable: pip3.6
