---

- name: Set sysctl Settings
  copy:
    src: 50-sysctl.conf
    dest: /etc/sysctl.d
    owner: root
    group: root
    mode: 0444

- name: Enable SELinux as Enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: Set hostname
  hostname: 
    name: "{{ shortHostName }}"
