---

- name: Set Permissions on sysctl.conf
  file:
    path: "/etc/sysctl.conf"
    owner: "root"
    group: "root"
    mode: "0444"

- name: Set sysctl Settings
  copy:
    src: 50-sysctl.conf
    dest: /etc/sysctl.d
    owner: root
    group: root
    mode: 0444

- name: Set HostName
  hostname:
    name: "{{ hostname }}"
