---

- name: Install Packages
  apt:
    name: "{{ query('flattened', ['{{packagesToInstall}}']) }}"
    state: latest

- name: Set Banner
  copy:
    src: banner
    dest: /etc/banner
    owner: root
    group: root
    mode: 0744
  notify: Restart ssh

- name: Enable SSH settings
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "{{ item }}"
  notify: Restart ssh
  with_items:
    - "{{ sshSettingsPresent }}"

- name: Disable SSH Settings
  lineinfile:
    path: /etc/ssh/sshd_config
    state: absent
    line: "{{ item }}"
  notify: Restart ssh
  with_items:
    - "{{ sshSettingsAbsent }}"

- name: Enable Services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ servicesToEnable }}"

- name: Disable Services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "{{ servicesToDisable }}"